---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
  - [krx2015, 2]
  - [scheduler, 2]
  - [third_party_writer, 2]
  - [third_party_next, 2]
  - [third_party_headline, 2]
  - [third_party_sso, 2]