#= require "ScrollToFixed/jquery-scrolltofixed-min"
#= require "widearea/minified/widearea.min"
#= require "tabulous/tabulous.min"
#= require "respond/dest/respond.min"
#= require "lazyloadxt/dist/jquery.lazyloadxt.min"
#= require "ladda/dist/spin.min"
#= require "ladda/dist/ladda.min"
#= require "magnific-popup/dist/jquery.magnific-popup.min"